### ISSUE TITLE
[Tutorial] How to decode ALFA SHELL V3!

### ISSUE THREAD

**Issue by raminfp** [solevisible/ALFA-SHELL-V3#3]
Hi @solevisible ,

I'm waiting of another obfuscation of your code,

Write-up: 
 https://github.com/raminfp/DeObfuscation_ALFA_SHELL_V3/

Thanks,
Ramin - kernel security engineering
Best regards,

**Comment by solevisible** [comment]
good job <3

**Comment by raminfp** [comment]
Thank you!
